version: "3.9"

services:
  node:
    build: infra-dev/node
    ports:
      - "3003:3003"
    volumes:
      - .:/srv/smarter-sharp
      - ./infra-dev/volumes/files:/shared/files
      - ./infra-dev/volumes/cache:/shared/cache
      - ~/.ssh:/home/node/.ssh
    environment:
      - NODE_OPTIONS="--max-old-space-size=8192"
    command:
      - 'nodemon'
      - '/srv/smarter-sharp/src/app.js'
      - '--basedir=/shared/files'
      - '--cachedir=/shared/cache'
